function addComponents(obj)

obj.handles.addMog = uicontrol('Style','pushbutton',...
    'String','Add MOG',...
    'Units','points',...
    'Callback',@obj.addMog,...
    'Parent',obj.handles.hp);
obj.handles.removeMog = uicontrol('Style','pushbutton',...
    'String','Remove MOG',...
    'Units','points',...
    'Callback',@obj.removeMog,...
    'Parent',obj.handles.hp);

obj.handles.listMogs = uicontrol('Style','listbox',...
    'Max',1,'Min',0,...
    'Units','points',...
    'Callback',@obj.listMogs,...
    'Parent',obj.handles.hp);

obj.handles.textType = uicontrol('Style','text',...
    'String','Type',...
    'HorizontalAlignment','right',...
    'Units','points',...
    'Parent',obj.handles.hp);
obj.handles.textTx = uicontrol('Style','text',...
    'String','Tx',...
    'HorizontalAlignment','right',...
    'Units','points',...
    'Parent',obj.handles.hp);
obj.handles.textRx = uicontrol('Style','text',...
    'String','Rx',...
    'HorizontalAlignment','right',...
    'Units','points',...
    'Parent',obj.handles.hp);

obj.handles.popupType = uicontrol('Style','popupmenu',...
    'String',{'Crosshole','VSP/VRP'},...
    'Units','points',...
    'Callback',@obj.popupType,...
    'Parent',obj.handles.hp);
obj.handles.popupTx = uicontrol('Style','popupmenu',...
    'String',' ',...
    'Units','points',...
    'Callback',@obj.popupTx,...
    'Parent',obj.handles.hp);
obj.handles.popupRx = uicontrol('Style','popupmenu',...
    'String',' ',...
    'Units','points',...
    'Callback',@obj.popupRx,...
    'Parent',obj.handles.hp);

obj.handles.useAirShots = uicontrol('Style','checkbox',...
    'String','Use Air Shots',...
    'Units','points',...
    'Callback',@obj.useAirShots,...
    'Parent',obj.handles.hp);
obj.handles.airBefore = uicontrol('Style','pushbutton',...
    'String','Air Shot Before',...
    'Units','points',...
    'Callback',@obj.airBefore,...
    'Parent',obj.handles.hp);
obj.handles.airAfter = uicontrol('Style','pushbutton',...
    'String','Air Shot After',...
    'Units','points',...
    'Callback',@obj.airAfter,...
    'Parent',obj.handles.hp);
obj.handles.textAirBefore = uicontrol('Style','text',...
    'BackgroundColor',[1 1 1],...
    'Units','points',...
    'Parent',obj.handles.hp);
obj.handles.textAirAfter = uicontrol('Style','text',...
    'BackgroundColor',[1 1 1],...
    'Units','points',...
    'Parent',obj.handles.hp);

obj.handles.renameMog = uicontrol('Style','pushbutton',...
    'String','Rename',...
    'Units','points',...
    'Callback',@obj.renameMog,...
    'Parent',obj.handles.hp);
obj.handles.importMog = uicontrol('Style','pushbutton',...
    'String','Import',...
    'Units','points',...
    'Callback',@obj.importMog,...
    'Parent',obj.handles.hp);
obj.handles.mergeMogs = uicontrol('Style','pushbutton',...
    'String','Merge',...
    'Units','points',...
    'Callback',@obj.mergeMogs,...
    'Parent',obj.handles.hp);
obj.handles.spectra = uicontrol('Style','pushbutton',...
    'String','Spectra',...
    'Units','points',...
    'Callback',@obj.spectra,...
    'Parent',obj.handles.hp);
obj.handles.rawData = uicontrol('Style','pushbutton',...
    'String','Raw Data',...
    'Units','points',...
    'Callback',@obj.rawData,...
    'Parent',obj.handles.hp);
obj.handles.zop = uicontrol('Style','pushbutton',...
    'String','Trace ZOP',...
    'Units','points',...
    'Callback',{@obj.zop,obj.bhUI},...
    'Parent',obj.handles.hp);

obj.handles.statsTt = uicontrol('Style','pushbutton',...
    'String','Stats tt',...
    'Units','points',...
    'Callback',@obj.statsTt,...
    'Parent',obj.handles.hp);
obj.handles.statsAmp = uicontrol('Style','pushbutton',...
    'String','Stats Ampl.',...
    'Units','points',...
    'Callback',@obj.statsAmp,...
    'Parent',obj.handles.hp);
obj.handles.rays = uicontrol('Style','pushbutton',...
    'String','Ray Coverage',...
    'Units','points',...
    'Callback',@obj.rays,...
    'Parent',obj.handles.hp);
obj.handles.exportTt = uicontrol('Style','pushbutton',...
    'String','Export tt',...
    'Units','points',...
    'Callback',@obj.exportTt,...
    'Parent',obj.handles.hp);
obj.handles.exportTau = uicontrol('Style','pushbutton',...
    'String',['Export ' char(964)],...
    'Units','points',...
    'Callback',@obj.exportTau,...
    'Parent',obj.handles.hp);
obj.handles.prune = uicontrol('Style','pushbutton',...
    'String','Prune',...
    'Units','points',...
    'ToolTipString','Trim Dataset',...
    'Callback',@obj.prune,...
    'Parent',obj.handles.hp);
obj.handles.createDt = uicontrol('Style','pushbutton',...
    'String',['Create ',char(916),'t MOG'],...
    'Units','points',...
    'ToolTipString',['Create New Mog Holding ',char(916),'t Data for Straight-Ray Time-Lapse Inversion'],...
    'Callback',@obj.createDt,...
    'Parent',obj.handles.hp);

obj.handles.textDate = uicontrol('Style','text',...
    'String','Date',...
    'HorizontalAlignment','right',...
    'Units','points',...
    'Parent',obj.handles.hp);
obj.handles.editDate = uicontrol('Style','edit',...
    'Units','points',...
    'Callback',@obj.editDate,...
    'Parent',obj.handles.hp);

obj.handles.textFreq = uicontrol('Style','text',...
    'String','Nominal Frequency of Antennas',...
    'HorizontalAlignment','right',...
    'Units','points',...
    'Parent',obj.handles.hp);
obj.handles.editFreq = uicontrol('Style','edit',...
    'Units','points',...
    'Callback',@obj.editFreq,...
    'Parent',obj.handles.hp);
obj.handles.textFeedRx = uicontrol('Style','text',...
    'String','Antenna Feedpoint Offset - Rx',...
    'HorizontalAlignment','right',...
    'Units','points',...
    'Parent',obj.handles.hp);
obj.handles.editFeedRx = uicontrol('Style','edit',...
    'Units','points',...
    'Callback',@obj.editFeedRx,...
    'Parent',obj.handles.hp);
obj.handles.textFeedTx = uicontrol('Style','text',...
    'String','Antenna Feedpoint Offset - Tx',...
    'HorizontalAlignment','right',...
    'Units','points',...
    'Parent',obj.handles.hp);
obj.handles.editFeedTx = uicontrol('Style','edit',...
    'Units','points',...
    'Callback',@obj.editFeedTx,...
    'Parent',obj.handles.hp);
obj.handles.checkDtCorr = uicontrol('Style','checkbox',...
    'String','Fixed Time Step Correction Factor',...
    'Units','points',...
    'Callback',@obj.checkDtCorr,...
    'Parent',obj.handles.hp);
obj.handles.editDtCorr = uicontrol('Style','edit',...
    'Units','points',...
    'Callback',@obj.editDtCorr,...
    'Parent',obj.handles.hp);
obj.handles.textMultFac = uicontrol('Style','text',...
    'String','Std dev. Multiplication Factor',...
    'HorizontalAlignment','right',...
    'Units','points',...
    'Parent',obj.handles.hp);
obj.handles.editMultFac = uicontrol('Style','edit',...
    'Units','points',...
    'Callback',@obj.editMultFac,...
    'Parent',obj.handles.hp);

end
