classdef BoreholeUI < handle
    %BOREHOLEUI User interface to manage Boreholes
    
    properties (SetAccess=private)
        boreholes
    end
    properties (Access=private)
        handles
    end
    
    methods
        function hp = getUIpanel(obj, varargin)
            %  Return a handle to the panel
            obj.createUI(varargin)
            hp = obj.handles.hp;
        end
    end
    
    methods (Access=private)
        function createUI(obj, args)
            width = 300;
            height = 360;
            obj.handles.hp = uipanel(args{:},...
                'Units','points',...
                'Title','Boreholes',...
                'Position',[5 5 width height], ...
                'Visible','off');
            
            obj.handles.addBH = uicontrol('Style','pushbutton',...
                'String','Add',...
                'Units','points',...
                'Position',[20 height-45 60 20], ...
                'Callback',@obj.addBH,...
                'Parent',obj.handles.hp);
            obj.handles.removeBH = uicontrol('Style','pushbutton',...
                'String','Remove',...
                'Units','points',...
                'Position',[85 height-45 60 20], ...
                'Callback',@obj.removeBH,...
                'Parent',obj.handles.hp);
            obj.handles.aimportBH = uicontrol('Style','pushbutton',...
                'String','Import',...
                'Units','points',...
                'Position',[150 height-45 60 20], ...
                'Callback',@obj.importBH,...
                'Parent',obj.handles.hp);
            obj.handles.plotBH = uicontrol('Style','pushbutton',...
                'String','Plot',...
                'Units','points',...
                'Position',[215 height-45 60 20], ...
                'Callback',@obj.plotBH,...
                'Parent',obj.handles.hp);

            obj.handles.listBH = uicontrol('Style','listbox',...
                'Max',1,'Min',0,...
                'Units','points',...
                'Position',[30 height-155 width-66 100],...
                'Callback',@obj.listBH,...
                'Parent',obj.handles.hp);
            
            obj.handles.textCoord = uicontrol('Style','text',...
                'String','Coordinates',...
                'Units','points',...
                'HorizontalAlignment','right',...
                'Position',[width/2-95 height-190 60 20], ...
                'Parent',obj.handles.hp);
            obj.handles.textX = uicontrol('Style','text',...
                'String','X:',...
                'Units','points',...
                'HorizontalAlignment','right',...
                'Position',[width/2-95 height-210 60 20], ...
                'Parent',obj.handles.hp);
            obj.handles.textY = uicontrol('Style','text',...
                'String','Y:',...
                'Units','points',...
                'HorizontalAlignment','right',...
                'Position',[width/2-95 height-235 60 20], ...
                'Parent',obj.handles.hp);
            obj.handles.textZ = uicontrol('Style','text',...
                'String','Elevation:',...
                'Units','points',...
                'HorizontalAlignment','right',...
                'Position',[width/2-95 height-260 60 20], ...
                'Parent',obj.handles.hp);
            obj.handles.textCollar = uicontrol('Style','text',...
                'String','Collar',...
                'Units','points',...
                'HorizontalAlignment','center',...
                'Position',[width/2-30 height-190 60 20], ...
                'Parent',obj.handles.hp);
            obj.handles.textBottom = uicontrol('Style','text',...
                'String','Bottom',...
                'Units','points',...
                'HorizontalAlignment','center',...
                'Position',[width/2+35 height-190 60 20], ...
                'Parent',obj.handles.hp);
            
            obj.handles.topX = uicontrol('Style','edit',...
                'Units','points',...
                'Callback',@obj.topX,...
                'Position',[width/2-30 height-210 60 20], ...
                'Parent',obj.handles.hp);
            obj.handles.topY = uicontrol('Style','edit',...
                'Units','points',...
                'Callback',@obj.topY,...
                'Position',[width/2-30 height-235 60 20], ...
                'Parent',obj.handles.hp);
            obj.handles.topZ = uicontrol('Style','edit',...
                'Units','points',...
                'Callback',@obj.topZ,...
                'Position',[width/2-30 height-260 60 20], ...
                'Parent',obj.handles.hp);
            obj.handles.bottomX = uicontrol('Style','edit',...
                'Units','points',...
                'Callback',@obj.bottomX,...
                'Position',[width/2+35 height-210 60 20], ...
                'Parent',obj.handles.hp);
            obj.handles.bottomY = uicontrol('Style','edit',...
                'Units','points',...
                'Callback',@obj.bottomY,...
                'Position',[width/2+35 height-235 60 20], ...
                'Parent',obj.handles.hp);
            obj.handles.bottomZ = uicontrol('Style','edit',...
                'Units','points',...
                'Callback',@obj.bottomZ,...
                'Position',[width/2+35 height-260 60 20], ...
                'Parent',obj.handles.hp);

            obj.handles.textZsurf = uicontrol('Style','text',...
                'String','Elevation at surface:',...
                'Units','points',...
                'HorizontalAlignment','right',...
                'Position',[width/2-105 height-285 100 20], ...
                'Parent',obj.handles.hp);
            obj.handles.Zsurf = uicontrol('Style','edit',...
                'Units','points',...
                'Callback',@obj.Zsurf,...
                'Position',[width/2 height-285 60 20], ...
                'Parent',obj.handles.hp);

            obj.handles.textZwater = uicontrol('Style','text',...
                'String','Elev. water:',...
                'Units','points',...
                'HorizontalAlignment','right',...
                'Position',[20 height-310 60 20], ...
                'Parent',obj.handles.hp);
            obj.handles.Zwater = uicontrol('Style','edit',...
                'Units','points',...
                'Callback',@obj.Zwater,...
                'Position',[85 height-310 60 20], ...
                'Parent',obj.handles.hp);

            obj.handles.textDiam = uicontrol('Style','text',...
                'String','Diameter:',...
                'Units','points',...
                'HorizontalAlignment','right',...
                'Position',[160 height-310 50 20], ...
                'Parent',obj.handles.hp);
            obj.handles.diameter = uicontrol('Style','edit',...
                'Units','points',...
                'Callback',@obj.diameter,...
                'Position',[215 height-310 60 20], ...
                'Parent',obj.handles.hp);

            obj.handles.contS = uicontrol('Style','pushbutton',...
                'String','Constraints slown.',...
                'Units','points',...
                'Position',[width/2-127 height-345 120 20], ...
                'Callback',@obj.contS,...
                'Parent',obj.handles.hp);
            obj.handles.contA = uicontrol('Style','pushbutton',...
                'String','Constraints atten.',...
                'Units','points',...
                'Position',[width/2+5 height-345 120 20], ...
                'Callback',@obj.contA,...
                'Parent',obj.handles.hp);

            obj.handles.hp.Visible = 'on';
        end
        
        
        function addBH(obj,varargin)
            name = inputdlg('Borehole name');
            if isempty(name)
                return;
            end
            if isempty(obj.boreholes)
                obj.boreholes = Borehole(char(name));
            else
                obj.boreholes(end+1) = Borehole(char(name));
            end
            names = cell(1,length(obj.boreholes));
            for n=1:length(obj.boreholes)
                names{n} = obj.boreholes(n).name;
            end
            obj.handles.listBH.String = names;
            obj.handles.listBH.Value = length(obj.boreholes);
            obj.updateEdits
        end
        function removeBH(obj, varargin)
            no = obj.handles.listBH.Value;
            ind=1:length(obj.boreholes);
            ind = ind~=no;

            obj.boreholes = obj.boreholes(ind);
            names = cell(1,length(obj.boreholes));
            for n=1:length(obj.boreholes)
                names{n} = obj.boreholes(n).name;
            end
            obj.handles.listBH.String = names;
            obj.handles.listBH.Value = length(obj.boreholes);
            obj.updateEdits
        end
        function importBH(obj, varargin)
            [filename, pathname] = uigetfile('*.xyz', 'Import borehole');
            if isequal(filename,0) || isequal(pathname,0)
                return
            else
                name = filename(1:end-4);
                fdata = load([pathname,filename]);
            end
            if isempty(obj.boreholes)
                obj.boreholes = Borehole(char(name));
            else
                obj.boreholes(end+1) = Borehole(char(name));
            end
            obj.boreholes(end).X = fdata(1,1);
            obj.boreholes(end).Y = fdata(1,2);
            obj.boreholes(end).Z = fdata(1,3);
            obj.boreholes(end).Xmax = fdata(end,1);
            obj.boreholes(end).Ymax = fdata(end,2);
            obj.boreholes(end).Zmax = fdata(end,3);
            obj.boreholes(end).fdata = fdata;

            names = cell(1,length(obj.boreholes));
            for n=1:length(obj.boreholes)
                names{n} = obj.boreholes(n).name;
            end
            obj.handles.listBH.String = names;
            obj.handles.listBH.Value = length(obj.boreholes);
            obj.updateEdits
        end
        function plotBH(obj, varargin)
            if isempty(obj.boreholes), return, end

            figure
            for n=1:length(obj.boreholes)
                plot3([obj.boreholes(n).X obj.boreholes(n).Xmax],...
                    [obj.boreholes(n).Y obj.boreholes(n).Ymax],...
                    [obj.boreholes(n).Z obj.boreholes(n).Zmax],'g','LineWidth',2)
                hold on
                plot3(obj.boreholes(n).X, obj.boreholes(n).Y, obj.boreholes(n).Z_surf,'ro')
                text(obj.boreholes(n).X, obj.boreholes(n).Y, ...
                    obj.boreholes(n).Z_surf, obj.boreholes(n).name)
            end
            grid on
            hold off
            xlabel('X [m]')
            ylabel('Y [m]')
            zlabel('Elevation [m]')
            set(gca,'DataAspectRatio',[1 1 1])

        end
        function listBH(obj,varargin)
            obj.updateEdits
        end
        function topX(obj, varargin)
            no = obj.handles.listBH.Value;
            if no>0 && no<=length(obj.boreholes)
                obj.boreholes(no).X = str2double( obj.handles.topX );
                obj.boreholes(no).fdata(1,1) = obj.boreholes(no).X;
            end
        end
        function topY(obj, varargin)
            no = obj.handles.listBH.Value;
            if no>0 && no<=length(obj.boreholes)
                obj.boreholes(no).Y = str2double( obj.handles.topY );
                obj.boreholes(no).fdata(1,2) = obj.boreholes(no).Y;
            end
        end
        function topZ(obj, varargin)
            no = obj.handles.listBH.Value;
            if no>0 && no<=length(obj.boreholes)
                obj.boreholes(no).Z = str2double( obj.handles.topZ );
                obj.boreholes(no).fdata(1,3) = obj.boreholes(no).Z;
            end

        end
        function bottomX(obj, varargin)
            no = obj.handles.listBH.Value;
            if no>0 && no<=length(obj.boreholes)
                obj.boreholes(no).Xmax = str2double( obj.handles.bottomX );
                obj.boreholes(no).fdata(end,1) = obj.boreholes(no).Xmax;
            end
        end
        function bottomY(obj, varargin)
            no = obj.handles.listBH.Value;
            if no>0 && no<=length(obj.boreholes)
                obj.boreholes(no).Ymax = str2double( obj.handles.bottomY );
                obj.boreholes(no).fdata(end,2) = obj.boreholes(no).Ymax;
            end
        end
        function bottomZ(obj, varargin)
            no = obj.handles.listBH.Value;
            if no>0 && no<=length(obj.boreholes)
                obj.boreholes(no).Zmax = str2double( obj.handles.bottomZ );
                obj.boreholes(no).fdata(end,3) = obj.boreholes(no).Zmax;
            end
        end
        function Zsurf(obj, varargin)
            no = obj.handles.listBH.Value;
            if no>0 && no<=length(obj.boreholes)
                obj.boreholes(no).Z_surf = str2double( obj.handles.Zsurf );
            end
        end
        function Zwater(obj, varargin)
            no = obj.handles.listBH.Value;
            if no>0 && no<=length(obj.boreholes)
                obj.boreholes(no).Z_water = str2double( obj.handles.Zwater );
            end
        end
        function diameter(obj, varargin)
            no = obj.handles.listBH.Value;
            if no>0 && no<=length(obj.boreholes)
                obj.boreholes(no).diam = str2double( obj.handles.diameter );
            end
        end
        function contS(obj, varargin)
            no = obj.handles.listBH.Value;
            if no>0 && no<=length(obj.boreholes)
                [file, rep] = uigetfile('*.con','Constraints file - Slowness');
                if file==0
                    return
                end
                cont = load([rep,file]);
                scont.x = obj.boreholes(no).X;    % vertical straight boreholes
                scont.y = obj.boreholes(no).Y;
                scont.z = obj.boreholes(no).Z - cont(:,1);
                scont.valeur = cont(:,2);
                if size(cont,2)==3
                    scont.variance = cont(:,3);
                else
                    scont.variance = zeros(size(cont(:,2)));
                end
                obj.boreholes(no).scont = scont;
            end
        end
        function contA(obj, varargin)
            no = obj.handles.listBH.Value;
            if no>0 && no<=length(obj.boreholes)
                [file, rep] = uigetfile('*.con','Constraints file - Attenuation');
                if file==0
                    return
                end
                cont = load([rep,file]);
                acont.x = obj.boreholes(no).X;    % vertical straight boreholes
                acont.y = obj.boreholes(no).Y;
                acont.z = obj.boreholes(no).Z - cont(:,1);
                acont.valeur = cont(:,2);
                if size(cont,2)==3
                    acont.variance = cont(:,3);
                else
                    acont.variance = zeros(size(cont(:,2)));
                end
                obj.boreholes(no).acont = acont;
            end
        end

        function updateEdits(obj)
            no = obj.handles.listBH.Value;
            if no>0 && no<=length(obj.boreholes)
                obj.handles.topX.String = num2str( obj.boreholes(no).X );
                obj.handles.topY.String = num2str( obj.boreholes(no).Y );
                obj.handles.topZ.String = num2str( obj.boreholes(no).Z );
                obj.handles.bottomX.String = num2str( obj.boreholes(no).Xmax );
                obj.handles.bottomY.String = num2str( obj.boreholes(no).Ymax );
                obj.handles.bottomZ.String = num2str( obj.boreholes(no).Zmax );
                obj.handles.Zsurf.String = num2str( obj.boreholes(no).Z_surf );
                obj.handles.Zwater.String = num2str( obj.boreholes(no).Z_water );
                obj.handles.diameter.String = num2str( obj.boreholes(no).diam );
            end
        end
    end
end
