function [ number,dbFile ] = chooseMOG( varargin )
%CHOOSEMOG Pick the number of a MOG in a database file

width = 250;
height = 175;
border = 25;
vBorder = 15;
vSize = 30;
fs = 11;
if ispc
    fs = 9;
end
position = [0 0 width height];
units = 'points';
position = mygetnicedialoglocation(position,units);
f = figure('Visible','off',...
    'Units',units,...
    'Position',position,...
    'Tag','chooseMOG',...
    'Name','Choose MOG',...
    'NumberTitle','off',...
    'ToolBar','none',...,
    'MenuBar','None',...
    'CloseRequestFcn',@closeWindow);

dbFile = '';
filename = '';
number = 0;
names_mog = ' ';
enableNewDB = 'on';
if nargin>=1
    if ischar(varargin{1})
        dbFile = varargin{1};
        filename = getDBname(dbFile);
        load(dbFile,'names_mog')
    elseif isa(varargin{1},'MogUI')
        names_mog = cell(1,length(varargin{1}.mogs));
        for n=1:length(varargin{1}.mogs)
            if isempty(varargin{1}.mogs(n).date)
                names_mog{n} = varargin{1}.mogs(n).name;
            else
                names_mog{n} = [varargin{1}.mogs(n).name, ' - ', varargin{1}.mogs(n).date];
            end
        end
        enableNewDB = 'off';
    end
end

uicontrol('Style','pushbutton',...
    'String','OK',...
    'Units',units,...
    'Fontsize',fs,...
    'Callback',@ok,...
    'Position',[border vBorder (width-3*border)/2 vSize],...
    'Parent',f);
uicontrol('Style','pushbutton',...
    'String','Cancel',...
    'Units',units,...
    'Fontsize',fs,...
    'Callback',@cancel,...
    'Position',[2*border+(width-3*border)/2 vBorder (width-3*border)/2 vSize],...
    'Parent',f);
hlist = uicontrol('Style','popupmenu',...
    'String',names_mog,...
    'Units',units,...
    'Fontsize',fs,...
    'Position',[width/4 1.5*vBorder+vSize width/2 vSize],...
    'Parent',f);
uicontrol('Style','pushbutton',...
    'String','Choose database',...
    'Units',units,...
    'Fontsize',fs,...
    'Callback',@db,...
    'Enable',enableNewDB,...
    'Position',[width/4 2*vBorder+2*vSize width/2 vSize],...
    'Parent',f);

hdbname = uicontrol('Style','text',...
    'BackgroundColor',[1 1 1],...
    'String',filename,...
    'Fontsize',fs,...
    'Units',units,...
    'Position',[border 2.5*vBorder+3*vSize width-2*border vSize],...
    'Parent',f);

f.Visible = 'on';
uiwait(f);

    function closeWindow(varargin)
        delete(f)
    end

    function ok(varargin)
        number = hlist.Value;
        delete(f)
    end
    function cancel(varargin)
        number = 0;
        delete(f)
    end
    function db(varargin)
        [file, rep] = uigetfile('*.mat','Choose DB');
        if isequal(file,0)
            return
        end
        try
            load([rep,file],'names_mog')
        catch ME
            errordlg(ME.message)
            return
        end
        dbFile = [rep,file];
        filename = getDBname(dbFile);
        hlist.String = names_mog;
        hdbname.String = file;
    end
end

